name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
name: Deploy Portfolio Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create deploy directory
        run: mkdir -p deploy

      - name: Copy Portfolio HTML
        run: |
          echo "Copying Portfolio Website..."
          cp mypro/Portfolioweb.html deploy/
