name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Portfolio HTML
        run: |
          echo "Deploying Portfolio Website..."
          # Here you can run commands to deploy or handle your HTML file
          cp mypro/Portfolioweb.html
